2020-03-17 09:54:45,533-root-INFO-日志信息：测试开始啦-[logger.py:28]
2020-03-17 09:54:45,533-root-ERROR-日志信息：测试报错啦-[logger.py:29]
2020-03-17 09:54:45,533-root-INFO-日志信息：测试结束-[logger.py:31]
2020-03-17 09:55:44,030-root-INFO-日志信息：测试开始啦-[logger.py:28]
2020-03-17 09:55:44,030-root-ERROR-日志信息：测试报错啦-[logger.py:29]
2020-03-17 09:55:44,030-root-INFO-日志信息：测试结束-[logger.py:31]
2020-03-17 09:56:11,493-case-INFO-日志信息：测试开始啦-[logger.py:28]
2020-03-17 09:56:11,494-case-ERROR-日志信息：测试报错啦-[logger.py:29]
2020-03-17 09:56:11,494-case-INFO-日志信息：测试结束-[logger.py:31]
2020-03-17 10:06:16,029-case-INFO-日志信息：测试开始啦-[logger.py:31]
2020-03-17 10:06:16,029-case-ERROR-日志信息：测试报错啦-[logger.py:32]
2020-03-17 10:06:16,029-case-INFO-日志信息：测试结束-[logger.py:34]
2020-03-17 10:36:29,178-case-INFO-日志信息：测试开始啦-[logger.py:31]
2020-03-17 10:36:29,178-case-ERROR-日志信息：测试报错啦-[logger.py:32]
2020-03-17 10:36:29,178-case-INFO-日志信息：测试结束-[logger.py:34]
2020-03-17 10:36:29,202-test_login-INFO-日志信息：准备测试前置-[test_login.py:20]
2020-03-17 10:36:29,204-test_login-INFO-日志信息：测试的title：正常的登录-[test_login.py:25]
2020-03-17 10:36:29,554-test_login-INFO-日志信息：结束测试：正常的登录-[test_login.py:34]
2020-03-17 10:36:29,555-test_login-INFO-日志信息：测试的title：手机号为空-[test_login.py:25]
2020-03-17 10:36:29,623-test_login-INFO-日志信息：结束测试：手机号为空-[test_login.py:34]
2020-03-17 10:36:29,624-test_login-INFO-日志信息：测试的title：密码为空-[test_login.py:25]
2020-03-17 10:36:29,693-test_login-INFO-日志信息：结束测试：密码为空-[test_login.py:34]
2020-03-17 10:36:29,694-test_login-INFO-日志信息：测试的title：用户名或密码错误-[test_login.py:25]
2020-03-17 10:36:29,910-test_login-INFO-日志信息：结束测试：用户名或密码错误-[test_login.py:34]
2020-03-17 10:36:29,910-test_login-INFO-日志信息：测试结束后置处理-[test_login.py:37]
2020-03-17 10:39:24,111-case-INFO-日志信息：测试开始啦-[logger.py:31]
2020-03-17 10:39:24,111-case-ERROR-日志信息：测试报错啦-[logger.py:32]
2020-03-17 10:39:24,111-case-INFO-日志信息：测试结束-[logger.py:34]
2020-03-17 10:39:24,129-test_login-INFO-日志信息：准备测试前置-[test_login.py:20]
2020-03-17 10:39:24,131-test_login-INFO-日志信息：测试的title：正常的登录-[test_login.py:25]
2020-03-17 10:39:24,421-test_login-INFO-日志信息：结束测试：正常的登录-[test_login.py:34]
2020-03-17 10:39:24,421-test_login-INFO-日志信息：测试的title：手机号为空-[test_login.py:25]
2020-03-17 10:39:24,489-test_login-INFO-日志信息：结束测试：手机号为空-[test_login.py:34]
2020-03-17 10:39:24,489-test_login-INFO-日志信息：测试的title：密码为空-[test_login.py:25]
2020-03-17 10:39:24,556-test_login-INFO-日志信息：结束测试：密码为空-[test_login.py:34]
2020-03-17 10:39:24,556-test_login-INFO-日志信息：测试的title：用户名或密码错误-[test_login.py:25]
2020-03-17 10:39:24,764-test_login-INFO-日志信息：结束测试：用户名或密码错误-[test_login.py:34]
2020-03-17 10:39:24,765-test_login-INFO-日志信息：测试结束后置处理-[test_login.py:37]
2020-03-17 10:52:00,270-case-INFO-日志信息：测试开始啦-[logger.py:31]
2020-03-17 10:52:00,270-case-ERROR-日志信息：测试报错啦-[logger.py:32]
2020-03-17 10:52:00,270-case-INFO-日志信息：测试结束-[logger.py:34]
2020-03-17 10:52:00,292-class_0314.testcase.test_login-INFO-日志信息：准备测试前置-[test_login.py:20]
2020-03-17 10:52:00,292-class_0314.testcase.test_login-INFO-日志信息：测试的title：正常的登录-[test_login.py:25]
2020-03-17 10:52:00,571-class_0314.testcase.test_login-INFO-日志信息：结束测试：正常的登录-[test_login.py:34]
2020-03-17 10:52:00,571-class_0314.testcase.test_login-INFO-日志信息：测试的title：手机号为空-[test_login.py:25]
2020-03-17 10:52:00,638-class_0314.testcase.test_login-INFO-日志信息：结束测试：手机号为空-[test_login.py:34]
2020-03-17 10:52:00,638-class_0314.testcase.test_login-INFO-日志信息：测试的title：密码为空-[test_login.py:25]
2020-03-17 10:52:00,705-class_0314.testcase.test_login-INFO-日志信息：结束测试：密码为空-[test_login.py:34]
2020-03-17 10:52:00,705-class_0314.testcase.test_login-INFO-日志信息：测试的title：用户名或密码错误-[test_login.py:25]
2020-03-17 10:52:00,910-class_0314.testcase.test_login-INFO-日志信息：结束测试：用户名或密码错误-[test_login.py:34]
2020-03-17 10:52:00,910-class_0314.testcase.test_login-INFO-日志信息：测试结束后置处理-[test_login.py:37]
2020-03-17 10:57:57,481-case-INFO-日志信息：测试开始啦-[logger.py:31]
2020-03-17 10:57:57,481-case-ERROR-日志信息：测试报错啦-[logger.py:32]
2020-03-17 10:57:57,481-case-INFO-日志信息：测试结束-[logger.py:34]
2020-03-17 10:58:00,119-test_login-INFO-日志信息：准备测试前置-[test_login.py:20]
2020-03-17 10:58:00,119-test_login-INFO-日志信息：测试的title：正常的登录-[test_login.py:25]
2020-03-17 10:58:00,374-test_login-INFO-日志信息：结束测试：正常的登录-[test_login.py:34]
2020-03-17 10:58:00,374-test_login-INFO-日志信息：测试的title：手机号为空-[test_login.py:25]
2020-03-17 10:58:00,444-test_login-INFO-日志信息：结束测试：手机号为空-[test_login.py:34]
2020-03-17 10:58:00,444-test_login-INFO-日志信息：测试的title：密码为空-[test_login.py:25]
2020-03-17 10:58:00,512-test_login-INFO-日志信息：结束测试：密码为空-[test_login.py:34]
2020-03-17 10:58:00,512-test_login-INFO-日志信息：测试的title：用户名或密码错误-[test_login.py:25]
2020-03-17 10:58:00,724-test_login-INFO-日志信息：结束测试：用户名或密码错误-[test_login.py:34]
2020-03-17 10:58:00,724-test_login-INFO-日志信息：测试结束后置处理-[test_login.py:37]
2020-03-17 11:01:44,518-case-INFO-日志信息：测试开始啦-[logger.py:31]
2020-03-17 11:01:44,518-case-ERROR-日志信息：测试报错啦-[logger.py:32]
2020-03-17 11:01:44,518-case-INFO-日志信息：测试结束-[logger.py:34]
2020-03-17 11:01:47,066-test_login-INFO-日志信息：准备测试前置-[test_login.py:20]
2020-03-17 11:01:47,067-test_login-INFO-日志信息：测试的title：正常的登录-[test_login.py:25]
2020-03-17 11:01:47,336-test_login-INFO-日志信息：结束测试：正常的登录-[test_login.py:34]
2020-03-17 11:01:47,336-test_login-INFO-日志信息：测试的title：手机号为空-[test_login.py:25]
2020-03-17 11:01:47,404-test_login-INFO-日志信息：结束测试：手机号为空-[test_login.py:34]
2020-03-17 11:01:47,404-test_login-INFO-日志信息：测试的title：密码为空-[test_login.py:25]
2020-03-17 11:01:47,472-test_login-INFO-日志信息：结束测试：密码为空-[test_login.py:34]
2020-03-17 11:01:47,473-test_login-INFO-日志信息：测试的title：用户名或密码错误-[test_login.py:25]
2020-03-17 11:01:47,710-test_login-INFO-日志信息：结束测试：用户名或密码错误-[test_login.py:34]
2020-03-17 11:01:47,710-test_login-INFO-日志信息：测试结束后置处理-[test_login.py:37]
